# Generated by Django 5.2.8 on 2026-06-09 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=16, verbose_name='連番')),
                ('customer_gc', models.CharField(blank=True, max_length=128, verbose_name='顧客グループ')),
                ('bill_to', models.CharField(blank=True, max_length=255, verbose_name='請求先会社名')),
                ('bill_cat', models.CharField(blank=True, max_length=16, verbose_name='区分')),
                ('currency', models.CharField(blank=True, default='CNY', max_length=8, verbose_name='通貨')),
                ('bill_year', models.IntegerField(blank=True, null=True, verbose_name='計上年')),
                ('bill_month', models.IntegerField(blank=True, null=True, verbose_name='計上月')),
                ('assignee', models.CharField(blank=True, max_length=64, verbose_name='担当者')),
                ('storage', models.FloatField(blank=True, null=True)),
                ('storage_rate', models.FloatField(blank=True, null=True)),
                ('warehouse', models.FloatField(blank=True, null=True)),
                ('warehouse_rate', models.FloatField(blank=True, null=True)),
                ('customs', models.FloatField(blank=True, null=True)),
                ('customs_rate', models.FloatField(blank=True, null=True)),
                ('service', models.FloatField(blank=True, null=True)),
                ('service_rate', models.FloatField(blank=True, null=True)),
                ('loc_transport', models.FloatField(blank=True, null=True)),
                ('loc_transport_rate', models.FloatField(blank=True, null=True)),
                ('disb', models.FloatField(blank=True, null=True)),
                ('disb_rate', models.FloatField(blank=True, null=True)),
                ('oth', models.FloatField(blank=True, null=True)),
                ('oth_rate', models.FloatField(blank=True, null=True)),
                ('tpl', models.FloatField(blank=True, null=True)),
                ('tpl_rate', models.FloatField(blank=True, null=True)),
                ('total_before_tax', models.FloatField(blank=True, null=True, verbose_name='税抜合計')),
                ('total_after_tax', models.FloatField(blank=True, null=True, verbose_name='税込合計')),
                ('exrate', models.FloatField(blank=True, null=True, verbose_name='為替レート')),
                ('rate_date', models.DateField(blank=True, null=True, verbose_name='レート日付')),
                ('fx_currency', models.CharField(blank=True, max_length=8, verbose_name='通貨')),
                ('converted_amount', models.FloatField(blank=True, null=True, verbose_name='換算後金額')),
                ('source', models.CharField(default='manual', max_length=16)),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='取消')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_lines', to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細',
                'ordering': ['-serial', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MasterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, verbose_name='グループ名')),
                ('company_name', models.CharField(max_length=255, verbose_name='会社名')),
                ('assignee', models.CharField(blank=True, max_length=64, verbose_name='担当者名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '取引先マスタ',
                'verbose_name_plural': '取引先マスタ',
                'ordering': ['group_name', 'company_name'],
                'constraints': [models.UniqueConstraint(fields=('group_name', 'company_name'), name='uniq_billing_group_company')],
            },
        ),
    ]
