# Generated by Django 5.2.8 on 2026-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_normalize_bill_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterparty',
            name='assignee',
        ),
        migrations.AddField(
            model_name='masterparty',
            name='business_summary',
            field=models.TextField(blank=True, verbose_name='業務概要'),
        ),
    ]
