# Generated by Django 5.2.8 on 2026-06-10 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_masterparty_assignee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認日時'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_approvals', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='承認済'),
        ),
    ]
