# Generated by Django 5.2.8 on 2026-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_mark_recent_unapproved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('bump', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '連番ロック',
                'verbose_name_plural': '連番ロック',
            },
        ),
    ]
