# Generated by Django 5.2.8 on 2026-06-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_dedupe_serials'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='exrate_multiply',
            field=models.BooleanField(default=False, verbose_name='レートを掛ける'),
        ),
    ]
