# Generated by Django 5.2.8 on 2025-11-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='訪問日')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='時間')),
                ('time_undecided', models.BooleanField(default=False, verbose_name='時間未定')),
                ('company_name', models.CharField(max_length=255, verbose_name='正式会社名')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='目的')),
                ('location', models.CharField(max_length=255, verbose_name='訪問場所')),
                ('host_staff', models.CharField(max_length=255, verbose_name='入力者')),
                ('cancelled', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['visit_date', 'visit_time', 'id'],
            },
        ),
    ]
