# Generated by Django 5.2.8 on 2025-12-02 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(default='09:00', verbose_name='送信時刻（毎日）')),
                ('mode', models.CharField(choices=[('django', 'Django 内部スケジューラで送信'), ('none', '自動送信なし（手動のみ）')], default='django', max_length=20, verbose_name='スケジューラ方式')),
                ('last_sent_date', models.DateField(blank=True, null=True, verbose_name='最終送信日')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='入力者ユーザー'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(max_length=255, verbose_name='訪問・WEB'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
