# Generated by Django 5.2.8 on 2026-06-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='顧客コード')),
                ('group_name', models.CharField(blank=True, max_length=128, verbose_name='グループ名')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='顧客名')),
                ('klass', models.CharField(choices=[('faurecia', 'Faurecia'), ('major', '大口顧客'), ('other', 'その他'), ('grey', 'グレー(調整・予估・外包)')], max_length=16, verbose_name='系列')),
                ('other_start_year', models.IntegerField(blank=True, null=True, verbose_name='その他開始年')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('amount', models.FloatField(verbose_name='売上')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales_trend.customer')),
            ],
            options={
                'verbose_name': '月別売上',
                'verbose_name_plural': '月別売上',
                'indexes': [models.Index(fields=['year', 'month'], name='sales_trend_year_8f9a3b_idx')],
            },
        ),
    ]
