# Generated by Django 5.2.8 on 2026-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100, verbose_name='モデル')),
                ('target_pk', models.CharField(max_length=64, verbose_name='対象pk')),
                ('action', models.CharField(default='update', max_length=40, verbose_name='操作種別')),
                ('before_json', models.JSONField(blank=True, default=dict, verbose_name='更新前')),
                ('after_json', models.JSONField(blank=True, default=dict, verbose_name='更新後')),
                ('actor', models.CharField(blank=True, default='', max_length=120, verbose_name='操作主体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
            ],
            options={
                'verbose_name': '汎用API監査ログ',
                'verbose_name_plural': '汎用API監査ログ',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpsProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=128, unique=True, verbose_name='リクエストnonce')),
                ('raw_body', models.TextField(blank=True, default='', verbose_name='受信本文(原文)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='処理日時')),
            ],
            options={
                'verbose_name': '汎用API処理済みリクエスト',
                'verbose_name_plural': '汎用API処理済みリクエスト',
            },
        ),
    ]
