# Generated by Django 5.2.8 on 2025-12-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=10, verbose_name='表示更新間隔（秒）')),
                ('cache_interval', models.IntegerField(default=300, verbose_name='キャッシュ取得間隔（秒）')),
                ('cache_expire_hours', models.IntegerField(default=168, verbose_name='キャッシュ保存期間（時間）')),
                ('log_directory', models.CharField(default='logs', max_length=255, verbose_name='ログ保存先ディレクトリ')),
                ('log_times', models.JSONField(default=list, verbose_name='ログ取得時刻リスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '温湿度設定',
                'verbose_name_plural': '温湿度設定',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='ロケーションID')),
                ('name', models.CharField(max_length=255, verbose_name='倉庫名')),
                ('is_external', models.BooleanField(default=False, verbose_name='外気測定用か')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ロケーション',
                'verbose_name_plural': 'ロケーション',
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='デバイスID（シリアル）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envmon.location', verbose_name='割当ロケーション')),
            ],
            options={
                'verbose_name': 'デバイス割当',
                'verbose_name_plural': 'デバイス割当',
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='デバイスID（シリアル）')),
                ('changed_at', models.DateTimeField(verbose_name='割当変更日時')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envmon.location', verbose_name='割当ロケーション')),
            ],
            options={
                'verbose_name': '割当履歴',
                'verbose_name_plural': '割当履歴',
                'indexes': [models.Index(fields=['device_id', 'changed_at'], name='envmon_assi_device__beec23_idx')],
            },
        ),
    ]
