# Generated by Django 5.2.8 on 2025-12-04 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='ログ時刻')),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='デバイスID（シリアル）')),
                ('warehouse', models.CharField(blank=True, max_length=255, verbose_name='倉庫名スナップショット')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('online', models.BooleanField(default=False, verbose_name='オンライン')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envmon.location', verbose_name='倉庫ロケーション')),
            ],
            options={
                'verbose_name': '温湿度ログ',
                'verbose_name_plural': '温湿度ログ',
                'indexes': [models.Index(fields=['timestamp', 'device_id'], name='envmon_envl_timesta_882e32_idx'), models.Index(fields=['timestamp', 'location'], name='envmon_envl_timesta_b88de3_idx')],
            },
        ),
    ]
