# Generated by Django 5.2.8 on 2025-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmon', '0002_envlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=64, verbose_name='シリアルナンバー')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='計測日時')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='生データ(JSON)')),
            ],
            options={
                'ordering': ['sn', 'recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('sn', 'recorded_at'), name='uniq_device_history_sn_recorded_at')],
            },
        ),
    ]
