# Generated by Django 5.2.8 on 2025-12-04 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmon', '0003_devicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='envsettings',
            name='history_fetch_time',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='履歴データ取得時刻（1日1回）'),
        ),
    ]
