# Generated by Django 5.2.8 on 2025-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmon', '0004_envsettings_history_fetch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='envsettings',
            name='is_fetching_history',
            field=models.BooleanField(default=False, verbose_name='履歴データ取得中フラグ'),
        ),
    ]
