# Generated by Django 5.2.8 on 2025-12-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envmon', '0005_envsettings_is_fetching_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvLog',
        ),
    ]
