# Generated by Django 5.2.8 on 2025-12-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmon', '0006_delete_envlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envsettings',
            name='cache_expire_hours',
            field=models.PositiveIntegerField(default=720),
        ),
        migrations.AlterField(
            model_name='envsettings',
            name='cache_interval',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='envsettings',
            name='interval',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
