# Generated by Django 5.2.8 on 2026-05-25 08:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(default=datetime.time(18, 0), verbose_name='送信時刻')),
                ('send_weekday', models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜'), (6, '日曜')], default=4, verbose_name='送信曜日')),
                ('mode', models.CharField(choices=[('django', 'Django 内部スケジューラで送信'), ('none', '自動送信なし（手動のみ）')], default='django', max_length=20, verbose_name='スケジューラ方式')),
                ('last_sent_date', models.DateField(blank=True, null=True, verbose_name='最終送信日')),
            ],
            options={
                'verbose_name': '週報送信設定',
                'verbose_name_plural': '週報送信設定',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportMailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='表示名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '週報メーリングリスト',
                'verbose_name_plural': '週報メーリングリスト',
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='進捗内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記入日時')),
                ('is_closed', models.BooleanField(default=False, verbose_name='クローズ')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='クローズ日時')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_progress_updates', to=settings.AUTH_USER_MODEL, verbose_name='記入者')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_progress_updates', to=settings.AUTH_USER_MODEL, verbose_name='クローズ操作者')),
            ],
            options={
                'verbose_name': '進捗',
                'verbose_name_plural': '進捗',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記入日時')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_supervisor_comments', to=settings.AUTH_USER_MODEL, verbose_name='上長')),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cs_tasks.progressupdate', verbose_name='進捗')),
            ],
            options={
                'verbose_name': '上長コメント',
                'verbose_name_plural': '上長コメント',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='課題名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='客先名')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('is_closed', models.BooleanField(default=False, verbose_name='完了')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='中止')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='中止日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='完了操作者')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'verbose_name': 'CS課題',
                'verbose_name_plural': 'CS課題',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='cs_tasks.task', verbose_name='課題'),
        ),
    ]
