# Generated by Django 5.2.8 on 2026-05-26 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorcomment',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cs_tasks.progressupdate', verbose_name='進捗'),
        ),
    ]
