# Generated by Django 5.2.8 on 2026-06-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0002_alter_supervisorcomment_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=128, unique=True, verbose_name='メッセージnonce')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='処理日時')),
            ],
            options={
                'verbose_name': 'ブリッジ処理済みメッセージ',
                'verbose_name_plural': 'ブリッジ処理済みメッセージ',
            },
        ),
        migrations.CreateModel(
            name='BridgeProcessedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(max_length=128, unique=True, verbose_name='操作ID')),
                ('action', models.CharField(max_length=40, verbose_name='操作種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='適用日時')),
            ],
            options={
                'verbose_name': 'ブリッジ処理済み操作',
                'verbose_name_plural': 'ブリッジ処理済み操作',
            },
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='content_ja',
            field=models.TextField(blank=True, verbose_name='進捗内容(日本語)'),
        ),
        migrations.AddField(
            model_name='supervisorcomment',
            name='content_ja',
            field=models.TextField(blank=True, verbose_name='コメント(日本語)'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ja',
            field=models.TextField(blank=True, verbose_name='詳細(日本語)'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ja',
            field=models.CharField(blank=True, max_length=255, verbose_name='課題名(日本語)'),
        ),
    ]
