# Generated by Django 5.2.8 on 2026-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0003_bridgeprocessedmessage_bridgeprocessedoperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='実施日'),
        ),
    ]
