# Generated by Django 5.2.8 on 2026-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0004_progressupdate_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('existing', '既存顧客課題'), ('new', '新規顧客課題'), ('internal', '部内課題')], default='existing', max_length=16, verbose_name='区分'),
        ),
    ]
