# Generated by Django 5.2.8 on 2026-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0006_bridgeprocessedoperation_result_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeprocessedmessage',
            name='raw_body',
            field=models.TextField(blank=True, default='', verbose_name='受信本文(原文)'),
        ),
        migrations.AddField(
            model_name='bridgeprocessedmessage',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=320, verbose_name='差出人'),
        ),
    ]
