# Generated by Django 5.2.8 on 2026-06-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0007_bridgeprocessedmessage_raw_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('existing', '既存顧客課題'), ('new', '新規顧客課題'), ('internal', '部内課題'), ('incident', 'インシデント (Bad News First)')], default='existing', max_length=16, verbose_name='区分'),
        ),
    ]
