# Generated by Django 5.2.8 on 2026-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0009_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreportconfig',
            name='body',
            field=models.TextField(blank=True, default='お疲れ様です。\n今週の CS 課題レポートを送付します。ご確認をお願いいたします。', help_text='この本文の下に、レポートの課題表が自動で挿入されます。', verbose_name='メール本文'),
        ),
        migrations.AddField(
            model_name='weeklyreportconfig',
            name='subject',
            field=models.CharField(blank=True, default='CS課題 週次レポート', max_length=255, verbose_name='メール件名'),
        ),
    ]
