# Generated by Django 5.2.8 on 2026-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0011_weeklyreportconfig_body_zh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreportconfig',
            name='source_lang',
            field=models.CharField(default='ja', max_length=8, verbose_name='翻訳元言語'),
        ),
        migrations.AddField(
            model_name='weeklyreportconfig',
            name='translated',
            field=models.BooleanField(default=True, verbose_name='相手言語へ翻訳済み'),
        ),
    ]
