# Generated by Django 5.2.8 on 2026-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_tasks', '0013_rename_task_cancelled_to_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='biz_status',
            field=models.CharField(blank=True, choices=[('negotiating', '交渉中'), ('won', '受注'), ('lost', '失注')], max_length=16, verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='task',
            name='biz_type',
            field=models.CharField(blank=True, choices=[('import', '輸入型'), ('export', '輸出型'), ('zone', '園区遊'), ('triangle', '3国間'), ('other', 'その他')], max_length=16, verbose_name='ビジネス形態'),
        ),
        migrations.AddField(
            model_name='task',
            name='biz_type_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='ビジネス形態(その他)'),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='予想売上(CNY)'),
        ),
        migrations.AddField(
            model_name='task',
            name='group_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='グループ内客先窓口'),
        ),
        migrations.AddField(
            model_name='task',
            name='revenue_type',
            field=models.CharField(blank=True, choices=[('recurring', '継続'), ('spot', 'スポット')], max_length=16, verbose_name='継続・スポット'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_month',
            field=models.DateField(blank=True, null=True, verbose_name='スタート時期'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_undecided',
            field=models.BooleanField(default=False, verbose_name='スタート時期未定'),
        ),
    ]
