# Generated by Django 5.2.8 on 2025-11-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例: visitor_notice, report_notice など', max_length=50, unique=True, verbose_name='アカウントコード')),
                ('name', models.CharField(max_length=100, verbose_name='アカウント名（説明用）')),
                ('smtp_host', models.CharField(default='smtp.qiye.aliyun.com', max_length=255, verbose_name='SMTPサーバー')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='ポート番号')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS を使用')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL を使用')),
                ('smtp_user', models.EmailField(blank=True, max_length=254, verbose_name='SMTPユーザー（ログインID / From）')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTPパスワード')),
                ('from_name', models.CharField(blank=True, default='NGLS-CS-INFO', max_length=255, verbose_name='送信者名（表示名）')),
            ],
        ),
    ]
