# Generated by Django 5.2.8 on 2025-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True, verbose_name='休日'),
        ),
        migrations.AlterField(
            model_name='visitmailconfig',
            name='send_time',
            field=models.TimeField(default='09:00', verbose_name='送信時刻（毎日）'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='正式会社名'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host_staff',
            field=models.CharField(max_length=255, verbose_name='入力者'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='location',
            field=models.CharField(max_length=255, verbose_name='訪問場所'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='目的'),
        ),
    ]
