# Generated by Django 5.2.8 on 2025-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_holiday_description_visitor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmailconfig',
            name='mode',
            field=models.CharField(choices=[('windows', 'Windows タスクスケジューラで送信'), ('django', 'Django 内部スケジューラで送信'), ('none', '自動送信なし（手動のみ）')], default='windows', max_length=20, verbose_name='スケジューラ方式'),
        ),
    ]
