# Generated by Django 5.2.8 on 2025-11-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitmailconfig_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
