# Generated by Django 5.2.8 on 2025-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_holidaydate_delete_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmailconfig',
            name='last_sent_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='最終自動送信日'),
        ),
    ]
