# Generated by Django 5.2.8 on 2025-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitmailconfig_last_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitmailconfig',
            name='last_sent_date',
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='from_name',
            field=models.CharField(blank=True, default='NGLS-CS-INFO', max_length=255, verbose_name='送信者名（表示名）'),
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='smtp_host',
            field=models.CharField(default='smtp.qiye.aliyun.com', max_length=255, verbose_name='SMTPサーバー'),
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTPパスワード'),
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='ポート番号'),
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='smtp_user',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SMTPユーザー（ログインID / From）'),
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='SSL を使用'),
        ),
        migrations.AddField(
            model_name='visitmailconfig',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS を使用'),
        ),
    ]
