# Generated by Django 5.2.8 on 2025-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_remove_visitmailconfig_last_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmailconfig',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終送信日'),
        ),
    ]
