# Generated by Django 5.2.8 on 2025-11-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_visitmailconfig_last_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='notes',
        ),
    ]
