# Generated by Django 5.2.8 on 2025-11-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_remove_visitor_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolidayDate',
        ),
    ]
