# Generated by Django 5.2.8 on 2026-06-11 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='荷主コード')),
                ('name', models.CharField(max_length=255, verbose_name='荷主名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '荷主マスタ',
                'verbose_name_plural': '荷主マスタ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=32, verbose_name='注文No')),
                ('order_received', models.DateField(blank=True, null=True, verbose_name='受注日')),
                ('inv_no', models.CharField(blank=True, max_length=64, verbose_name='インボイスNo')),
                ('dest', models.CharField(blank=True, max_length=32, verbose_name='仕向地')),
                ('out_ctn', models.IntegerField(blank=True, null=True, verbose_name='カートン数')),
                ('out_m3', models.FloatField(blank=True, null=True, verbose_name='容積(M³)')),
                ('out_qty', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('container_type', models.CharField(blank=True, max_length=16, verbose_name='輸送区分')),
                ('vessel', models.CharField(blank=True, max_length=96, verbose_name='本船名')),
                ('voyage', models.CharField(blank=True, max_length=48, verbose_name='航海No')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='出港予定 ETD')),
                ('cy_cut', models.DateField(blank=True, null=True, verbose_name='CY搬入')),
                ('cy_open', models.DateField(blank=True, null=True, verbose_name='CYオープン')),
                ('vanning', models.DateField(blank=True, null=True, verbose_name='バンニング')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='入港予定 ETA')),
                ('atd', models.DateField(blank=True, null=True, verbose_name='出港実績 ATD')),
                ('ata', models.DateField(blank=True, null=True, verbose_name='入港実績 ATA')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('assignee', models.CharField(blank=True, max_length=64, verbose_name='担当者')),
                ('source', models.CharField(default='manual', max_length=16)),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='取消')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='vessel_tracking.customer', verbose_name='荷主')),
            ],
            options={
                'verbose_name': '出荷トレーシング',
                'verbose_name_plural': '出荷トレーシング',
                'ordering': ['-etd', '-id'],
            },
        ),
    ]
