# Generated by Django 5.2.8 on 2026-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_tracking', '0002_load_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shanghai_ata',
            field=models.DateField(blank=True, null=True, verbose_name='上海入港'),
        ),
    ]
