# Generated by Django 5.2.8 on 2026-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_tracking', '0003_shipment_shanghai_ata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shanghai_eta',
            field=models.DateField(blank=True, null=True, verbose_name='上海入港予定'),
        ),
    ]
