# Generated by Django 5.2.8 on 2026-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_tracking', '0004_shipment_shanghai_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cy_open_act',
            field=models.DateField(blank=True, null=True, verbose_name='ACYオープン'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, max_length=32, verbose_name='仕出地'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cy_open',
            field=models.DateField(blank=True, null=True, verbose_name='ECYオープン'),
        ),
    ]
