# Generated by Django 5.2.8 on 2026-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_tracking', '0005_shipment_cy_open_act_shipment_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='live_dest_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_dest_unlocode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_nav_status',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='live_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
