# Generated by Django 5.2.8 on 2026-06-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_tracking', '0006_shipment_live_dest_name_shipment_live_dest_unlocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='container_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='コンテナ本数'),
        ),
    ]
