# Generated by Django 5.2.8 on 2025-11-19 14:29

import authsys.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authsys.models.UserManager()),
            ],
        ),
    ]
