# Generated by Django 5.2.8 on 2025-11-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='初回ログイン時にパスワード変更が必要'),
        ),
    ]
