# Generated by Django 5.2.8 on 2025-11-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='休日日付')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称（任意）')),
            ],
            options={
                'verbose_name': '休日',
                'verbose_name_plural': '休日マスタ',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='特別稼働日')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称（任意）')),
            ],
            options={
                'verbose_name': '特別稼働日',
                'verbose_name_plural': '特別稼働日マスタ',
                'ordering': ['date'],
            },
        ),
    ]
