"""
Django settings for intranet_portal project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@j!+8sxq!196-=_&k4f&0j9ezgu99mvpefeob@a$9y)tu4b98*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '10.214.80.86',
    'localhost',
    '127.0.0.1',
    'bridge.deucenet.app',   # CSブリッジ リアルタイム連携API(Cloudflare Tunnel経由)
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'authsys',
    'visitors.apps.VisitorsConfig',
    "meetings.apps.MeetingsConfig",
    'working_schedule',
    'mailcenter',
    'envmon',
    'scheduler.apps.SchedulerConfig',
    'cs_tasks.apps.CsTasksConfig',
    'billing.apps.BillingConfig',
    'sales_trend.apps.SalesTrendConfig',
    'vessel_tracking.apps.VesselTrackingConfig',
    'opsbridge.apps.OpsbridgeConfig',
    'contacts.apps.ContactsConfig',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "authsys.middleware.ForcePasswordChangeMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intranet_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # ← ここを追加/修正
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]


WSGI_APPLICATION = 'intranet_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Waitress はマルチスレッドで SQLite に同時書き込みする。既定(DEFERRED)だと
        # 「読んでから書く」トランザクションがロック昇格で即 "database is locked" に
        # なり busy timeout が効かない。IMMEDIATE で開始時に書込ロックを取り、競合は
        # timeout 秒だけ待って直列化する。WAL で読み取りは書き込みにブロックされない。
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

LANGUAGES = [
    ('ja', 'Japanese'),
    ('zh-hans', 'Chinese (Simplified)'),
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# カスタムユーザーモデル
AUTH_USER_MODEL = 'authsys.User'

LOGIN_URL = 'authsys:login'
LOGIN_REDIRECT_URL = '/'      # or 'home'
LOGOUT_REDIRECT_URL = 'authsys:login'     # ログアウト後もポータルへ

# メール設定（Aliyun 企業メール）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qiye.aliyun.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = 'cs_info@ngls.sh.cn'
EMAIL_HOST_PASSWORD = 'NGLScs9981'

EMAIL_USE_TLS = True   # ← TLS（STARTTLS）を使う
EMAIL_USE_SSL = False  # ← SSLは使わない

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =========================================================
# CS課題 翻訳ブリッジ(管理者用Macアプリ連携)
# 機密値(HMAC鍵・受信箱パスワード)は環境変数から読む。
# リポジトリにはコミットしないこと。
# =========================================================
# 復路の署名検証用 共有秘密鍵(必須。未設定なら writeback は全拒否)
CS_BRIDGE_HMAC_SECRET = os.environ.get('CS_BRIDGE_HMAC_SECRET', '')

# リアルタイム連携API(メール置換)のBearerトークン。未設定なら API は全拒否(フェイルクローズ)。
# Mac(cs_bridge)はこのトークンで sync/writeback を呼ぶ。本番は更に Cloudflare Access で多層防御。
CS_BRIDGE_API_TOKEN = os.environ.get('CS_BRIDGE_API_TOKEN', '')

# =========================================================
# opsbridge: 汎用メンテナンス用 export/writeback API のホワイトリスト。
#   認証は上の CS_BRIDGE_API_TOKEN(Bearer) と CS_BRIDGE_HMAC_SECRET(writeback署名) を再利用。
#   export は読取専用。writeback はモデル単位＋フィールド単位で許可を限定。
# =========================================================
# export 許可モデル(ラベル集合)。ここに無いモデルは 403。
OPSBRIDGE_EXPORT_MODELS = {
    "visitors.Visitor",
    "meetings.Meeting",
}

# writeback 許可: model_label -> 更新を許可するフィールド集合。
#   ここに無いモデル/フィールドへの更新は拒否。cancelled(論理削除)は意図的に含めない。
OPSBRIDGE_WRITEBACK_MODELS = {
    "visitors.Visitor": {"company_name", "last_name", "first_name", "title"},
    "meetings.Meeting": {"company_name", "last_name", "first_name", "title"},
}

# (廃止) 復路メールの差出人許可リスト。メール経路撤去済み。API は Bearerトークン認証のため未使用。
# inbound.apply_writeback の enforce_sender=True 既定の後方互換のためだけに残置。
CS_BRIDGE_ALLOWED_SENDERS = [
    s.strip() for s in os.environ.get('CS_BRIDGE_ALLOWED_SENDERS', '').split(',') if s.strip()
]

# (廃止) 往路 同期メールの宛先。メール経路撤去済み(往路は API bridge_sync)。未使用。
CS_BRIDGE_SYNC_RECIPIENTS = [
    s.strip() for s in os.environ.get('CS_BRIDGE_SYNC_RECIPIENTS', '').split(',') if s.strip()
]

# ブリッジ起票/反映の操作主体にするユーザー(email)。空ならauthor=null
CS_BRIDGE_AUTHOR_EMAIL = os.environ.get('CS_BRIDGE_AUTHOR_EMAIL', '')

# (廃止) 往路メール送信に使っていた MailAccount.code。メール経路撤去済み。未使用。
CS_BRIDGE_MAIL_ACCOUNT = os.environ.get('CS_BRIDGE_MAIL_ACCOUNT', 'cs_report')

# 受信箱(IMAP)。メール経路撤去後は「溜まったブリッジメールの一回限り掃除」(cs_inbound_purge)で使用。
# 未設定時は cs_inbound_purge が MailAccount(来客通知の送信アカウント)の資格情報へフォールバックする。
CS_BRIDGE_INTAKE_IMAP_HOST = os.environ.get('CS_BRIDGE_INTAKE_IMAP_HOST', '')
CS_BRIDGE_INTAKE_IMAP_PORT = int(os.environ.get('CS_BRIDGE_INTAKE_IMAP_PORT', '993'))
CS_BRIDGE_INTAKE_IMAP_USER = os.environ.get('CS_BRIDGE_INTAKE_IMAP_USER', '')
CS_BRIDGE_INTAKE_IMAP_PASSWORD = os.environ.get('CS_BRIDGE_INTAKE_IMAP_PASSWORD', '')
CS_BRIDGE_INTAKE_IMAP_SSL = os.environ.get('CS_BRIDGE_INTAKE_IMAP_SSL', '1') not in ('0', 'false', 'False', '')
CS_BRIDGE_INTAKE_MAILBOX = os.environ.get('CS_BRIDGE_INTAKE_MAILBOX', 'INBOX')

VISITORS_SCHEDULER_MODE = 'windows'  # 'windows' / 'django' / 'none'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        # visitors/scheduler.py の logger(__name__) → "visitors.scheduler"
        "visitors.scheduler": {
            "handlers": ["console"],
            "level": "INFO",   # tick ログなどを出したいので INFO
            "propagate": False,
        },
        # meetings のメール送信ログ等も見たければ
        "meetings": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
